2020-08-25 19:14:36 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-25 19:15:55 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-28 18:20:07 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-28 18:21:40 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 26
2020-08-29 11:41:20 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 39
2020-08-29 11:41:43 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 39
2020-08-29 19:25:14 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-29 19:25:23 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-29 19:26:52 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-29 19:27:02 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-30 05:08:43 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\new_product.html on line 30
2020-08-30 05:08:49 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\new_product.html on line 30
2020-08-30 05:08:52 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\new_product.html on line 30
2020-08-30 10:14:02 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-30 11:10:28 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\edit_product.html on line 34
2020-08-30 16:16:24 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 16:18:10 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 16:19:57 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 16:24:16 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 16:30:18 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 16:35:08 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 61
2020-08-30 17:06:25 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 62
2020-08-30 17:10:10 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 101
2020-08-30 17:15:58 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 101
2020-08-30 18:54:15 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 83
2020-08-31 04:24:04 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 04:36:17 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 04:46:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 04:51:38 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 12:29:55 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 12:30:57 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 12:31:57 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 12:33:54 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-08-31 19:41:14 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\edit_product.html on line 67
2020-09-01 11:49:17 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 196
2020-09-01 12:24:46 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 9
2020-09-01 12:44:41 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 16
2020-09-01 13:05:19 - ERROR - FileNotFoundError in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py on line 1074
2020-09-01 13:06:00 - ERROR - FileNotFoundError in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py on line 1074
2020-09-01 13:09:05 - ERROR - FileNotFoundError in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py on line 1074
2020-09-05 12:34:18 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 31
2020-09-05 13:06:15 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 33
2020-09-05 13:35:12 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\edit_portfolio.html on line 4
2020-09-05 13:47:12 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\edit_portfolio.html on line 4
2020-09-05 14:10:37 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio.html on line 17
2020-09-05 14:10:41 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio.html on line 17
2020-09-05 14:15:07 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 128
2020-09-05 14:15:42 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 128
2020-09-05 14:16:14 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 128
2020-09-05 14:18:59 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 128
2020-09-05 14:19:17 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 128
2020-09-05 14:33:24 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\edit_portfolio.html on line 21
2020-09-05 17:49:41 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 30
2020-09-05 19:51:01 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 16
2020-09-07 12:11:28 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 6
2020-09-08 16:23:26 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-08 16:25:38 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-08 16:27:50 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-08 16:29:26 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-08 16:30:54 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-08 16:33:19 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-09 06:21:14 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 12
2020-09-09 06:23:23 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 19
2020-09-09 06:42:36 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-09 06:43:48 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-09 10:05:06 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 85
2020-09-09 10:06:01 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 85
2020-09-09 18:44:43 - ERROR - TemplateNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 210
2020-09-09 18:45:15 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-09 18:45:40 - ERROR - TemplateNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 210
2020-09-09 19:18:08 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\choose_related_products.html on line 10
2020-09-10 20:48:13 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-10 20:49:16 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 141
2020-09-11 18:40:27 - ERROR - TemplateNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 225
2020-09-11 19:54:46 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 46
2020-09-11 19:56:37 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 30
2020-09-11 20:07:30 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-12 07:55:26 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 25
2020-09-12 07:59:41 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 23
2020-09-12 08:01:53 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 70
2020-09-12 08:38:20 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 23
2020-09-12 08:47:02 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 23
2020-09-12 08:51:26 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 23
2020-09-12 08:53:24 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 13
2020-09-12 08:58:07 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 8
2020-09-12 10:09:17 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-12 10:09:52 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-12 10:09:54 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-12 10:20:25 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\new_product.html on line 27
2020-09-14 04:50:46 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\new_product.html on line 27
2020-09-14 05:08:59 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 145
2020-09-14 05:09:22 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 145
2020-09-14 05:11:57 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-14 05:12:09 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-14 05:15:25 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 145
2020-09-14 05:19:20 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 145
2020-09-14 05:21:45 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\portfolio_header.html on line 24
2020-09-14 05:24:14 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_portfolio.html on line 38
2020-09-14 07:53:01 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:53:43 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:54:46 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:56:04 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:57:32 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:58:02 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 07:58:12 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 08:03:35 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-14 08:04:00 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 117
2020-09-14 12:30:51 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\MainController.py on line 21
2020-09-15 04:31:35 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-15 04:32:25 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-15 04:35:18 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-09-15 04:59:05 - ERROR - FileNotFoundError in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 234
2020-10-01 05:45:15 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 194
2020-10-01 05:59:29 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 194
2020-10-02 04:07:27 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\MainController.py on line 23
2020-10-02 04:10:01 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\MainController.py on line 23
2020-10-03 19:51:47 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\middleware\AdminMiddleware.py on line 19
2020-10-03 19:54:14 - ERROR - RouteException in F:\Personal\prog\web\_m_test\app\http\middleware\AdminMiddleware.py on line 20
2020-10-04 07:21:28 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\middleware\AdminMiddleware.py on line 19
2020-10-04 07:26:08 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\middleware\AdminMiddleware.py on line 19
2020-10-04 19:04:58 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\middleware\AdminMiddleware.py on line 19
2020-10-05 05:49:04 - ERROR - ModuleNotFoundError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 20
2020-10-05 05:50:20 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 41
2020-10-05 06:05:44 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 41
2020-10-05 10:37:11 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 41
2020-10-06 16:28:21 - ERROR - NameError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 32
2020-10-06 16:56:31 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:03:37 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:04:22 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 50
2020-10-06 17:05:23 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 51
2020-10-06 17:06:12 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:30:28 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\menu.html on line 50
2020-10-06 17:31:56 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:34:00 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:39:38 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-06 17:40:23 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 44
2020-10-06 18:11:31 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 23
2020-10-06 18:13:53 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 23
2020-10-06 18:14:02 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 23
2020-10-06 20:10:02 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-07 04:25:23 - ERROR - ModuleNotFoundError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 60
2020-10-07 11:13:04 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2020-10-07 11:13:15 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2020-10-07 18:03:21 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:05:14 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:06:20 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:08:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:08:10 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:11:17 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:11:55 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2020-10-08 12:14:16 - ERROR - UnboundLocalError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 92
2021-01-21 07:27:51 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-01-21 07:27:57 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-01-21 07:29:01 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-01-22 13:43:50 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 33
2021-01-22 13:44:07 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 33
2021-01-26 20:01:09 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 44
2021-01-26 20:02:44 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\new_address.html on line 12
2021-01-26 20:03:11 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\new_address.html on line 12
2021-01-31 11:21:16 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\menu.html on line 44
2021-01-31 11:43:25 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-15 12:26:33 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\menu.html on line 50
2021-02-15 19:10:56 - ERROR - gaierror in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\socket.py on line 748
2021-02-15 19:12:20 - ERROR - SMTPServerDisconnected in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 394
2021-02-15 19:14:14 - ERROR - SMTPServerDisconnected in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 394
2021-02-15 19:18:27 - ERROR - SMTPServerDisconnected in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 394
2021-02-15 19:23:40 - ERROR - SMTPServerDisconnected in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 394
2021-02-20 14:11:02 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 133
2021-02-20 14:21:35 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 150
2021-02-20 14:25:37 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 153
2021-02-20 15:01:42 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-20 16:17:47 - ERROR - ModuleNotFoundError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 218
2021-02-20 21:33:15 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\single_order.html on line 68
2021-02-20 21:45:12 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 52
2021-02-21 07:20:09 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 73
2021-02-21 07:27:30 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 133
2021-02-21 08:38:20 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 08:40:21 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 08:41:45 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 08:48:47 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 08:50:44 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 08:55:10 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 10:20:47 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 64
2021-02-21 11:30:41 - ERROR - UnboundLocalError in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 72
2021-02-21 11:33:13 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\resources\templates\auth\register.html on line 14
2021-02-21 11:38:19 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\auth\RegisterController.py on line 71
2021-02-21 11:43:57 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 11:45:32 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\resources\templates\auth\register.html on line 14
2021-02-21 15:17:01 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 15:19:28 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 15:43:06 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 16:04:01 - ERROR - SMTPRecipientsRefused in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 881
2021-02-21 17:13:34 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 17:14:14 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 17:15:55 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 18:32:40 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 18:33:29 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 18:35:45 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 43
2021-02-21 18:37:27 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 44
2021-02-21 18:41:54 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 45
2021-02-21 18:42:22 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 45
2021-02-21 18:42:51 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 45
2021-02-21 18:43:33 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 46
2021-02-21 18:50:01 - ERROR - InvalidToken in F:\Personal\prog\web\_m_test\app\http\controllers\auth\ConfirmController.py on line 45
2021-02-21 18:52:02 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-21 21:15:57 - ERROR - TemplateAssertionError in F:\Personal\prog\web\_m_test\resources\templates\dash\profile.html on line 15
2021-02-22 10:43:34 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\auth\forget.html on line 29
2021-02-22 10:44:39 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\auth\forget.html on line 29
2021-02-22 10:45:07 - ERROR - SMTPSenderRefused in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 867
2021-02-22 10:59:57 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\auth\PasswordController.py on line 47
2021-02-22 11:02:13 - ERROR - SMTPSenderRefused in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 867
2021-02-22 11:08:48 - ERROR - SMTPServerDisconnected in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py on line 394
2021-02-22 11:11:23 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\auth\forget.html on line 29
2021-02-22 11:15:36 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\auth\forget.html on line 29
2021-02-22 11:17:04 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\auth\forget.html on line 29
2021-02-22 13:06:37 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 50
2021-02-22 13:12:06 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-22 13:12:11 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-23 13:31:23 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-23 13:37:08 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 62
2021-02-23 13:45:53 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-23 13:47:55 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-23 13:48:47 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-23 13:49:40 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-23 13:50:32 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-23 13:50:54 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 64
2021-02-24 14:16:27 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 30
2021-02-24 14:17:01 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 31
2021-02-24 14:17:04 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 31
2021-02-24 14:25:54 - ERROR - TemplateNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 54
2021-02-24 14:37:47 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-24 14:38:20 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-24 21:17:37 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 329
2021-02-24 21:19:30 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 329
2021-02-24 21:20:49 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 329
2021-02-25 05:35:50 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-25 09:40:32 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 64
2021-02-25 10:02:10 - ERROR - ModuleNotFoundError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminUsersController.py on line 32
2021-02-25 10:07:01 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\users\all.html on line 29
2021-02-25 10:07:47 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\users\all.html on line 29
2021-02-25 10:10:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-25 10:10:06 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-25 10:10:15 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-02-25 10:10:40 - ERROR - KeyError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminUsersController.py on line 32
2021-02-25 10:10:41 - ERROR - KeyError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminUsersController.py on line 32
2021-02-25 10:13:40 - ERROR - KeyError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminUsersController.py on line 32
2021-02-25 12:00:11 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 39
2021-02-25 12:00:33 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 39
2021-02-26 16:17:10 - ERROR - ParserError in F:\Personal\prog\web\_m_test\app\http\controllers\AdminOrdersController.py on line 39
2021-02-27 13:14:18 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 8
2021-02-27 13:14:51 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 8
2021-02-28 15:36:35 - ERROR - FileTypeException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 262
2021-03-08 10:42:00 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\menu.html on line 53
2021-03-08 11:43:17 - ERROR - TemplateNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\MainController.py on line 44
2021-03-11 20:49:58 - ERROR - ResponseError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-11 21:06:47 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 159
2021-03-11 21:07:01 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 159
2021-03-11 21:08:07 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 159
2021-03-11 21:08:46 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 159
2021-03-11 21:17:50 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 236
2021-03-12 08:35:42 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 08:47:58 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 186
2021-03-12 08:49:37 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 08:56:10 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 08:58:19 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 09:00:54 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 187
2021-03-12 09:02:57 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 188
2021-03-12 09:07:48 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 189
2021-03-12 09:08:36 - ERROR - JSONDecodeError in C:\Users\pkrssak\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py on line 353
2021-03-12 09:12:44 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 09:19:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 10:38:33 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 10:40:56 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 10:45:46 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 16:28:06 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 16:49:24 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 20:45:04 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 20:54:51 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\dash\cart.html on line 26
2021-03-12 21:19:29 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 224
2021-03-12 21:28:37 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 228
2021-03-12 21:32:38 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 236
2021-03-12 21:35:54 - ERROR - ValueError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 236
2021-03-12 21:43:31 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 21:44:04 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 21:59:27 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:16:42 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:16:45 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:26:27 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:26:30 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:40:17 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-12 22:43:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 04:48:58 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 04:49:48 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 236
2021-03-13 04:50:57 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 236
2021-03-13 04:52:22 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 236
2021-03-13 04:55:56 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 237
2021-03-13 04:58:04 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 245
2021-03-13 04:59:21 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 246
2021-03-13 04:59:24 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 246
2021-03-13 05:00:25 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 246
2021-03-13 05:04:03 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 167
2021-03-13 05:04:40 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 167
2021-03-13 12:17:09 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 12:18:06 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 12:29:32 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\dash\single_order.html on line 44
2021-03-13 12:45:48 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 12:48:44 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 359
2021-03-13 12:49:56 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\DashboardController.py on line 360
2021-03-13 12:51:35 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 12:53:47 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 12:54:59 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 13:21:40 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 13:23:37 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-13 15:28:53 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 223
2021-03-13 16:27:28 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 225
2021-03-13 20:33:55 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 210
2021-03-13 20:33:58 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\edit_product.html on line 210
2021-03-13 21:24:21 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 102
2021-03-13 21:24:24 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 102
2021-03-13 21:27:21 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 102
2021-03-13 21:27:56 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 102
2021-03-13 21:37:23 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 117
2021-03-13 21:42:44 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 102
2021-03-14 11:27:09 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 115
2021-03-14 11:27:12 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 115
2021-03-14 11:27:24 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\product.html on line 115
2021-03-27 19:37:52 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 58
2021-03-27 19:54:09 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\InvoiceController.py on line 36
2021-03-27 19:55:07 - ERROR - ModelNotFound in F:\Personal\prog\web\_m_test\app\http\controllers\InvoiceController.py on line 35
2021-03-27 20:01:15 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\InvoiceController.py on line 33
2021-03-27 20:41:50 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-27 20:43:09 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-27 20:43:28 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-27 20:46:00 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-27 20:48:19 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\InvoiceController.py on line 86
2021-03-27 20:50:30 - ERROR - KeyError in F:\Personal\prog\web\_m_test\app\tools\invoice.py on line 318
2021-03-28 09:58:45 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 162
2021-03-28 09:58:48 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 162
2021-03-28 09:59:59 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 162
2021-03-28 10:01:24 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:04:13 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:04:35 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:04:38 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:06:02 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:06:16 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 163
2021-03-28 10:06:58 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:07:17 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:07:47 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:07:57 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:09:37 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:10:55 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 168
2021-03-28 10:14:03 - ERROR - ContainerError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-03-28 10:32:42 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 161
2021-03-28 10:32:46 - ERROR - TemplateSyntaxError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 161
2021-03-28 10:34:31 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 164
2021-03-28 10:40:42 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 166
2021-03-28 10:41:52 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 167
2021-03-28 10:47:31 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\orders\one.html on line 167
2021-03-29 13:11:35 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 215
2021-03-29 13:12:16 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\EditPortfolioController.py on line 215
2021-03-29 13:12:26 - ERROR - SyntaxError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-04-01 11:20:25 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 112
2021-04-01 12:24:47 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 112
2021-04-03 05:15:56 - ERROR - QueryException in F:\Personal\prog\web\_m_test\app\http\controllers\PortfolioController.py on line 58
2021-04-04 11:40:23 - ERROR - AttributeError in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
2021-04-04 11:56:53 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\top_products\setup.html on line 23
2021-04-04 11:57:40 - ERROR - UndefinedError in F:\Personal\prog\web\_m_test\resources\templates\admin\top_products\setup.html on line 25
2021-04-04 12:22:07 - ERROR - InvalidCSRFToken in F:\Personal\prog\web\_m_test\bootstrap\start.py on line 38
